# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Rant Master's Den
  it: L'antro del Rant Master
email: davidedelpapa@gmail.com
description:
  en: Personal site mainly for blogging purpose. I'm interested in programming, gardening, and much more
  it: Sito personale per bloggare sui miei interessi, principalmente informatica, ma anche giardinaggio, etc, etc...
index:
  en:
  it: benvenuti.html
feed:
  en: /feed.xml
  it: /flux.xml
#baseurl: "/jekyll-multilingual" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: oldMammuth
github_username:  oldmammuth

# Build settings
markdown: kramdown
